baseURL: /
languageCode: en-us
theme: raditian-free-hugo-theme-data-science
params:
  footer:
    copyright: Â© Matt Dancho. All rights reserved.
    site_logo:
      _2x: img/general/business-science-logo.png
      alt: Design & Code - Business Science
      x: img/general/business-science-logo.png
  googleAnalyticsID: ''
  logo:
    text1: Xilena
    text2: Suarez
  plugins:
    css:
      - URL: css/main.css
      - URL: css/rad-icons.css
      - URL: css/custom.css
    js:
      - URL: js/rad-animations.js
      - URL: js/sticky-header.js
      - URL: js/library/fontfaceobserver.js
  sections:
    - showcase
    - about
    - client-and-work
    - experience
    - education
    - testimonial
    - contact
    - newsletter
menu:
  footer:
    - URL: '#about'
      name: Conoceme
      weight: 2
    - URL: '#portfolio'
      name: Portafolio
      weight: 3
    - URL: '#contact'
      name: Contactame
      weight: 4
  header:
    - URL: '#about'
      name: Conoceme
      weight: 2
    - URL: '#portfolio'
      name: Portafolio
      weight: 3
    - URL: '#contact'
      name: Contactame
      weight: 4